# Generated by Django 4.2.5 on 2023-09-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userchatroomdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChatRoomDetails',
        ),
    ]
