# Generated by Django 4.2.5 on 2023-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_is_banned_reportedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='private_channel_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
