# Generated by Django 4.2.5 on 2023-09-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_users_last_activity_users_private_channel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
